version: '3.8'

services:
  backend:
    build:
      context: ./Emotion_Draw/api/
      dockerfile: .dockerfile
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./Emotion_Draw/client/
      dockerfile: .dockerfile
    ports:
      - "3000:3000"
    restart: always